<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\Repositories\FluentCMS.Infrastructure.Repositories\FluentCMS.Infrastructure.Repositories.csproj" />
    <ProjectReference Include="..\FluentCMS.Api.Core.Models\FluentCMS.Api.Core.Models.csproj" />
  </ItemGroup>

</Project>
