<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluentCMS.Configuration.EntityFramework\FluentCMS.Configuration.EntityFramework.csproj" />
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
    </ItemGroup>
    
</Project>
