<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluentCMS.Api.Core.Services\FluentCMS.Api.Core.Services.csproj" />
  </ItemGroup>

</Project>
