<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.9" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    </ItemGroup>


    <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Configuration\FluentCMS.Infrastructure.Configuration.EntityFramework.Sqlite\FluentCMS.Infrastructure.Configuration.EntityFramework.Sqlite.csproj" />
    <ProjectReference Include="..\..\Infrastructure\EventBus\FluentCMS.Infrastructure.EventBus.InMemory\FluentCMS.Infrastructure.EventBus.InMemory.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Logging\FluentCMS.Infrastructure.Logging\FluentCMS.Infrastructure.Logging.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Plugins\FluentCMS.Infrastructure.Plugins\FluentCMS.Infrastructure.Plugins.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Providers\FluentCMS.Infrastructure.Providers.Repositories.EntityFramework\FluentCMS.Infrastructure.Providers.Repositories.EntityFramework.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Repositories\FluentCMS.Infrastructure.Repositories.EntityFramework.Sqlite\FluentCMS.Infrastructure.Repositories.EntityFramework.Sqlite.csproj" />
    <ProjectReference Include="..\Plugins\FluentCMS.Api.Plugins.AuditTrailManagement\FluentCMS.Api.Plugins.AuditTrailManagement.csproj" />
    <ProjectReference Include="..\Plugins\FluentCMS.Api.Plugins.TodoManagement\FluentCMS.Api.Plugins.TodoManagement.csproj" />
    <ProjectReference Include="..\Providers\Caching\FluentCMS.Api.Providers.Caching.InMemory\FluentCMS.Api.Providers.Caching.InMemory.csproj" />
    <ProjectReference Include="..\Providers\Email\FluentCMS.Api.Providers.Email.Null\FluentCMS.Api.Providers.Email.Null.csproj" />
    <ProjectReference Include="..\Providers\Email\FluentCMS.Api.Providers.Email.Smtp\FluentCMS.Api.Providers.Email.Smtp.csproj" />
  </ItemGroup>


    <ItemGroup>
      <Folder Include="Repositories\Abstractions\" />
    </ItemGroup>

</Project>
