<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\Configuration\FluentCMS.Infrastructure.Configuration\FluentCMS.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\FluentCMS.Infrastructure.Identity\FluentCMS.Infrastructure.Identity.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\FluentCMS.Infrastructure\FluentCMS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Plugins\FluentCMS.Infrastructure.Plugins.Abstractions\FluentCMS.Infrastructure.Plugins.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Repositories\FluentCMS.Infrastructure.Repositories.EntityFramework\FluentCMS.Infrastructure.Repositories.EntityFramework.csproj" />
    <ProjectReference Include="..\FluentCMS.Api.Plugins.Models\FluentCMS.Api.Plugins.Models.csproj" />
  </ItemGroup>

</Project>
