global using AutoMapper;
global using FluentCMS.Web.ApiClients;
global using FluentCMS.Web.UI.Components;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.WebUtilities;
global using Microsoft.JSInterop;
global using System.Web;
