<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\Exceptions\FluentCMS.Infrastructure.Exceptions\FluentCMS.Infrastructure.Exceptions.csproj" />
    <ProjectReference Include="..\..\Providers\Email\FluentCMS.Api.Providers.Email.Abstractions\FluentCMS.Api.Providers.Email.Abstractions.csproj" />
    <ProjectReference Include="..\..\Providers\FileStorage\FluentCMS.Api.Providers.FileStorage.Abstractions\FluentCMS.Api.Providers.FileStorage.Abstractions.csproj" />
    <ProjectReference Include="..\FluentCMS.Api.Core.Repositories.Abstractions\FluentCMS.Api.Core.Repositories.Abstractions.csproj" />
  </ItemGroup>

</Project>
